language: python
dist: xenial
matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

services: xvfb
cache: pip

addons:
  apt:
    packages:
    - gfortran
    - libncurses5-dev

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes True --set changeps1 False
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Create conda test environment
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy pandas xarray requests dask toolz netCDF4 portalocker pytest-cov pytest-ordering
  - conda activate test-environment
  # Get latest coveralls from pip, not conda
  - pip install coveralls pytest-flake8
  # Dependencies not available through conda, install through pip
  - pip install pysatCDF >/dev/null
  # Custom pysat install
  - cd ..
  - git clone --single-branch --branch develop-3 https://github.com/pysat/pysat.git
  - cd pysat
  - python setup.py install
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  # set up data directory
  - mkdir /home/travis/build/pysatData
  - cd ../pysatSpaceWeather
  # install pysatSpaceWeather
  - python setup.py install

# command to run tests
script:
 - pytest -vs --flake8 --cov=pysatSpaceWeather/

after_success:
 - coveralls --rcfile=setup.cfg
